export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const GET_USERS = 'GET_USERS'
export const LOAD_USERS = 'LOAD_USERS'
export const SELECT_USER = 'SELECT_USER'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const LOAD_EVENTS = 'LOAD_EVENTS'
export const CURRENT_EVENTS = 'CURRENT_EVENTS'
export const EVENT_FILTER = 'EVENT_FILTER'
export const SELECT_EVENT = 'SELECT_EVENT'
export const UNSELECT_EVENT = 'UNSELECT_EVENT'

export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const ADD_LIKE = 'ADD_LIKE'
export const DELETE_LIKE = 'DELETE_LIKE'
